url: http://rires-eveilles.fr/
baseurl:

# Site settings
title: Rires Éveillés - Yoga du rire - Cours et ateliers pour particuliers et entreprises
email: contact@rires-eveilles.fr
description: "Le yoga du rire, éveillé ! Des cours de yoga du rire à Paris, des ateliers de yoga du rire pour les entreprises, des événements autour du yoga du rire... vous allez rire !"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/yogarireseveilles/

collections:
  cours:
    title: cours
    output: false
  evenements:
    title: evenements
    output: false

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    blog: true
    title: ''
    description: ''
    img: ''
    comments: ''
- scope:
    path: ''
    type: cours
  values:
    title: ''
    background-color: ''
    adresse: ''
    moment: ''
    booking: ''
    prix-libre: ''
- scope:
    path: ''
    type: evenements
  values:
    title: ''
    background-color: ''
    infos: ''
    adresse: ''
    moment: ''
    lien: ''
    booking: ''


# Build settings
markdown: kramdown
permalink: "/blog/:title"
